training_data = [
    # Greeting
    ("hello", "greeting"),
    ("hi", "greeting"),
    ("hey", "greeting"),
    ("hello there", "greeting"),
    ("hey chatbot", "greeting"),
    ("hi there", "greeting"),
    ("good morning", "greeting"),
    ("good evening", "greeting"),
    ("can you help me", "greeting"),
    ("hello campus swap", "greeting"),

    # Search
    ("show me laptops", "search_item"),
    ("find me a laptop", "search_item"),
    ("I need a calculator", "search_item"),
    ("show me books", "search_item"),
    ("find engineering books", "search_item"),
    ("do you have headphones", "search_item"),
    ("I am looking for a laptop", "search_item"),
    ("show available items", "search_item"),
    ("find me a book", "search_item"),
    ("I am looking for books", "search_item"),
    ("do you have a calculator", "search_item"),
    ("can you find a laptop", "search_item"),
    ("I need a laptop", "search_item"),
    ("I need headphones", "search_item"),
    ("show me available laptops", "search_item"),
    ("find books for me", "search_item"),
    ("where can I find a laptop", "search_item"),
    ("search for a calculator", "search_item"),
    ("look for headphones", "search_item"),
    ("I want to find a book", "search_item"),

    # Sell
    ("I want to sell something", "sell_item"),
    ("how can I sell an item", "sell_item"),
    ("I want to list my book", "sell_item"),
    ("how do I sell my laptop", "sell_item"),
    ("I want to put an item for sale", "sell_item"),
    ("I want to sell a book", "sell_item"),
    ("I want to sell my laptop", "sell_item"),
    ("I want to sell my calculator", "sell_item"),
    ("how do I list an item", "sell_item"),
    ("how can I list something", "sell_item"),
    ("how do I put something for sale", "sell_item"),
    ("I have something to sell", "sell_item"),
    ("I need to sell an item", "sell_item"),
    ("I want to post an item", "sell_item"),
    ("how can I post an item", "sell_item"),
    ("where can I sell my item", "sell_item"),
    ("I want to create a listing", "sell_item"),
    ("how do I create a listing", "sell_item"),
    ("I want to list a laptop", "sell_item"),
    ("I want to list a book for sale", "sell_item"),

    # Buy
    ("I want to buy something", "buy_item"),
    ("how can I buy an item", "buy_item"),
    ("I want to purchase a laptop", "buy_item"),
    ("how do I buy something", "buy_item"),
    ("I want to buy a laptop", "buy_item"),
    ("I want to buy a book", "buy_item"),
    ("I need to purchase something", "buy_item"),
    ("where can I buy an item", "buy_item"),
    ("how do I purchase an item", "buy_item"),
    ("I want to purchase a book", "buy_item"),

    # Contact seller
    ("how do I contact the seller", "contact_seller"),
    ("can I message the seller", "contact_seller"),
    ("how can I talk to the seller", "contact_seller"),
    ("I want to contact the seller", "contact_seller"),
    ("how do I message a seller", "contact_seller"),
    ("can I contact the person selling this", "contact_seller"),
    ("how can I reach the seller", "contact_seller"),
    ("I need to talk to the seller", "contact_seller"),

    # Platform information
    ("what is campus swap", "platform_info"),
    ("how does campus swap work", "platform_info"),
    ("what can I do on campus swap", "platform_info"),
    ("tell me about campus swap", "platform_info"),
    ("what is this website", "platform_info"),
    ("what is this platform", "platform_info"),
    ("what is campus swap used for", "platform_info"),
    ("how does this platform work", "platform_info"),

    # Problems
    ("something is not working", "report_problem"),
    ("I have a problem", "report_problem"),
    ("I found a bug", "report_problem"),
    ("the website is not working", "report_problem"),
    ("something went wrong", "report_problem"),
    ("I am having a problem", "report_problem"),
    ("there is an error", "report_problem"),
    ("the website has a problem", "report_problem"),
    ("I want to report a problem", "report_problem"),

    # Goodbye
    ("bye", "goodbye"),
    ("goodbye", "goodbye"),
    ("see you", "goodbye"),
    ("thanks bye", "goodbye"),
    ("see you later", "goodbye"),
    ("thank you goodbye", "goodbye"),
    ("bye chatbot", "goodbye")
]